"edit_uri": ""
"extra_css":
  - "stylesheets/extra.css"
"markdown_extensions":
  - "pymdownx.highlight"
  - "pymdownx.superfences"
"plugins":
  - "search":
      "indexing": "titles"
      "min_search_length": 2
      "prebuild_index": true
      "separator": "[\\s\\-\\.]+"
  - "minify":
      "minify_html": true
"repo_name": "mintel/kubernetes-external-secrets-libsonnet"
"repo_url": "https://github.com/mintel/kubernetes-external-secrets-libsonnet"
"site_name": "kubernetes-external-secrets jsonnet library"
"site_url": "https://mintel.github.io/kubernetes-external-secrets-libsonnet"
"theme":
  "name": "material"
  "palette":
    - "accent": "indigo"
      "media": "(prefers-color-scheme: light)"
      "primary": "indigo"
      "scheme": "default"
      "toggle":
        "icon": "material/toggle-switch-off-outline"
        "name": "Switch to dark mode"
    - "accent": "red"
      "media": "(prefers-color-scheme: dark)"
      "primary": "red"
      "scheme": "slate"
      "toggle":
        "icon": "material/toggle-switch"
        "name": "Switch to light mode"